title: scratch-cat-goes-skiing-scratch2
hero_image: images/banner.png
description: scratch-cat-goes-skiing-scratch2 description
version: 4
listed: false
copyedit: false
last_tested: "2019-01-21"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
